# mkdocs.yml
site_name: "hikari-crescent documentation"
site_url: https://hikari-crescent.github.io/
repo_url: https://github.com/hikari-crescent/hikari-crescent
copyright: Copyright &copy; 2022 crescent maintainers
edit_uri: edit/main/docs/
theme:
  name: material
  icon:
    logo: octicons/moon-24
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-off-outline
        name: Switch to light mode
  features:
    - content.tabs.link
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - navigation.tabs
    - content.action.view
    - content.action.edit
    - content.tooltips
    - toc.follow
    - toc.integrate


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - autorefs
  - search
  - social
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["", "crescent/ext/"]
          import:
            - https://docs.python.org/3.8/objects.inv
            - https://docs.hikari-py.dev/en/latest/objects.inv
          options:
            heading_level: 3
            annotations_path: source
            docstring_section_style: spacy
            docstring_style: google
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            show_source: false
            show_submodules: false
            signature_crossrefs: true
            show_symbol_type_heading: true
            extensions:
                - griffe_inherited_docstrings
nav:
  - Welcome to Crescent: index.md
  - getting_started.md
  - Guides:
    - guides/index.md
    - guides/commands.md
    - guides/plugins.md
    - guides/events.md
    - guides/hooks.md
    - guides/error_handling.md
    - Extension Libraries:
      - guides/ext/cooldowns.md
      - guides/ext/tasks.md
      - guides/ext/locales.md
  - API Reference:
    - api_reference/index.md
    - api_reference/client.md
    - api_reference/commands.md
    - api_reference/context.md
    - api_reference/events.md
    - api_reference/errors.md
    - api_reference/plugin.md
    - api_reference/locale.md
    - api_reference/typedefs.md
    - api_reference/mentionable.md
    - api_reference/exceptions.md
    - Extension Libraries:
      - api_reference/ext/cooldowns.md
      - api_reference/ext/tasks.md
      - api_reference/ext/locales.md

watch:
  - docs
  - README.md
  - crescent
