name: auto-merge-dependabot

on:
  pull_request:

jobs:
  auto-merge-dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GH_TOKEN }}
