name: ci
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/setup-uv@v7
      - run: uv python install
      - run: uv sync --all-extras --dev
      - run: uv run ruff check
        if: ${{ !cancelled() }}
      - run: uv run codespell crescent
        if: ${{ !cancelled() }}
      - run: uv run codespell docs
        if: ${{ !cancelled() }}
      - run: uv run mypy .
        if: ${{ !cancelled() }}
      - run: uv run pyright
        if: ${{ !cancelled() }}
      - run: uv run pyright --verifytypes crescent --ignoreexternal
        if: ${{ !cancelled() }}
      - run: uv run mkdocs -q build
        if: ${{ !cancelled() }}

  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12', '3.13', '3.14']
        os: ['ubuntu']
      fail-fast: false

    name: test python ${{ matrix.python }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python }}
      - run: uv python install
      - run: uv sync --all-extras --dev
      - run: uv run pytest tests/crescent
