name: Build Docs

on: [push, pull_request]

jobs:
  check-build:
    name: Check docs build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: run pdoc
        run: |
          poetry install
          ./docs/build.sh
