name: pypi

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/setup-uv@v7

      - run: uv version "$(git describe --tags --abbrev=0 | sed 's/^v//')" --frozen
      - run: uv build
      - name: Run uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish

  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/setup-uv@v7

      - run: uv sync --all-extras --dev
      - run: uv run mkdocs -q build

      - uses: actions/setup-node@v2
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
