name: Pyright
on: [push, pull_request]
jobs:
  pyright:
    name: pyright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: run Pyright
        run: |
          poetry install
          poetry run pyright
          poetry run pyright --verifytypes crescent
